# This file was generated by GoReleaser. DO NOT EDIT.
cask "jev-cli" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "11f095bb2b8eb40cab4f5922742714b7192d3b8fe06f48150f813d02062aa5a8"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "397eb248cee795a47437f33bfe6d8852a5d9ba32d60693ba76f00674c953e92b"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ed2941312258084ff73a343e5ffede846b99dbccfcae548f72f0e98b25737cb7"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3bb89c781286e403e7ba3400fd38558c5059b34ef4d384ab07eb91cc1631a00d"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jev-cli"
  desc "Read less and decide with calibrated confidence through TypeSafe's Jev model"
  homepage "https://github.com/bragamat/jevkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jev-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jev-cli"]
    end
  end

  # No zap stanza required
end
