# This file was generated by GoReleaser. DO NOT EDIT.
cask "jev-cli" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "4f3556b91912288718ed84dab512262ebccf9c6edaffb0e9c370db21283042cf"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "60df65b4af2a2fecaef5a4560d66f1572b39089295ddc29fe7aa653799ad6450"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3860d8ee8f931e1e17d6a1f37cc6c665d63a75825343a2f00e88b7b1f80f6b95"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8db59347c33438b32dcc49898fd7f4c586a6f4f74ff99aadf4d0b60d4133fda0"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jev-cli"
  desc "Read less and decide with calibrated confidence through TypeSafe's Jev model"
  homepage "https://github.com/bragamat/jevkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jev-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jev-cli"]
    end
  end

  # No zap stanza required
end
