# This file was generated by GoReleaser. DO NOT EDIT.
cask "jev" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "f068e5136868bfacf1addfac1a5793d4701ba8cf2de01c28d4b642c27246111e"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c171327d099589ef99c18298b3070016ce51f55a91237555d65fd1a719a697b7"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c91b92308969b90c36b5e794041610acb17b802e86c7f22f51da7950527945bf"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "24c619a65146a16e39c7b20b0faf417a025fd95ac8bccec3ea70e9cef46bf542"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jev"
  desc "Read less and decide with calibrated confidence through TypeSafe's Jev model"
  homepage "https://github.com/bragamat/jevkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jev"]
    end
  end

  # No zap stanza required
end
