# This file was generated by GoReleaser. DO NOT EDIT.
cask "jev" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "d9d75de9f8c959a19af70917eeb3a12d253cdf158f8da74d323ceaf961cd2b5a"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "383c53278ece52658d9edb137acdd712e966c656206ad972c21bcfd1cb1704a5"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "253715f8169b98cbfd94f3d64fd3ff55b37d731007659d8531934d26128172a5"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9aff1d51aaca5ef31e3d53964a6cbd37bc31125a0ac1035826f54ac210caeb3f"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jev"
  desc "Read less and decide with calibrated confidence through TypeSafe's Jev model"
  homepage "https://github.com/bragamat/jevkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jev"]
    end
  end

  # No zap stanza required
end
