# This file was generated by GoReleaser. DO NOT EDIT.
cask "jev" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "632b8f90e2dfb690eaabc2cdb095051785d2363891abf4a32eb6150b8f8d972e"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "45b571b196dad4f818548031d4654690e7f7919d4f43151ecb3fddf2d2318d9f"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1cbc14f083326d2f010cbf39f42ee3a978f53887dd7ec3355946d6efd59d6dad"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d86af76870b0d8cfb0857b150edb1b17c7dfe80d94543b4e38ea7106d1a50a84"
      url "https://github.com/bragamat/jevkit/releases/download/v#{version}/jevkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jev"
  desc "Read less and decide with calibrated confidence through TypeSafe's Jev model"
  homepage "https://github.com/bragamat/jevkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jev"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jev"]
    end
  end

  # No zap stanza required
end
